[tool.poetry]
name = "py-what"
version = "0.1.0"
description = ""
authors = ["Cangsong W. <cwang40@slb.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
